package com.manage.dao.entity;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAccountHda<M extends BaseAccountHda<M>> extends Model<M> implements IBean {

	public void setAccountId(java.lang.Integer accountId) {
		set("account_id", accountId);
	}

	public java.lang.Integer getAccountId() {
		return get("account_id");
	}

	public void setVipNo(java.lang.String vipNo) {
		set("vip_no", vipNo);
	}

	public java.lang.String getVipNo() {
		return get("vip_no");
	}

	public void setNum(java.lang.String num) {
		set("num", num);
	}

	public java.lang.String getNum() {
		return get("num");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	public java.lang.String getStatus() {
		return get("status");
	}

	public void setFirstBonusTimes(java.lang.Integer firstBonusTimes) {
		set("first_bonus_times", firstBonusTimes);
	}

	public java.lang.Integer getFirstBonusTimes() {
		return get("first_bonus_times");
	}

	public void setShareBonusTimes(java.lang.Integer shareBonusTimes) {
		set("share_bonus_times", shareBonusTimes);
	}

	public java.lang.Integer getShareBonusTimes() {
		return get("share_bonus_times");
	}

	public void setBonusAmount(java.lang.String bonusAmount) {
		set("bonus_amount", bonusAmount);
	}

	public java.lang.String getBonusAmount() {
		return get("bonus_amount");
	}

	public void setCreateTime(java.lang.String createTime) {
		set("create_time", createTime);
	}

	public java.lang.String getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.lang.String updateTime) {
		set("update_time", updateTime);
	}

	public java.lang.String getUpdateTime() {
		return get("update_time");
	}

}
