package com.manage.dao.entity;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAccountLock<M extends BaseAccountLock<M>> extends Model<M> implements IBean {

	public void setLockId(java.lang.Integer lockId) {
		set("lock_id", lockId);
	}

	public java.lang.Integer getLockId() {
		return get("lock_id");
	}

	public void setVipNo(java.lang.String vipNo) {
		set("vip_no", vipNo);
	}

	public java.lang.String getVipNo() {
		return get("vip_no");
	}

	public void setLockBalance(java.lang.String lockBalance) {
		set("lock_balance", lockBalance);
	}

	public java.lang.String getLockBalance() {
		return get("lock_balance");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

}
