package com.manage.dao.entity;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLogAccountHda<M extends BaseLogAccountHda<M>> extends Model<M> implements IBean {

	public void setLogId(java.lang.Integer logId) {
		set("log_id", logId);
	}

	public java.lang.Integer getLogId() {
		return get("log_id");
	}

	public void setAccountId(java.lang.Integer accountId) {
		set("account_id", accountId);
	}

	public java.lang.Integer getAccountId() {
		return get("account_id");
	}

	public void setVipNo(java.lang.String vipNo) {
		set("vip_no", vipNo);
	}

	public java.lang.String getVipNo() {
		return get("vip_no");
	}

	public void setBeforeNum(java.lang.String beforeNum) {
		set("before_num", beforeNum);
	}

	public java.lang.String getBeforeNum() {
		return get("before_num");
	}

	public void setTradeNum(java.lang.String tradeNum) {
		set("trade_num", tradeNum);
	}

	public java.lang.String getTradeNum() {
		return get("trade_num");
	}

	public void setAfterNum(java.lang.String afterNum) {
		set("after_num", afterNum);
	}

	public java.lang.String getAfterNum() {
		return get("after_num");
	}

	public void setTradeType(java.lang.String tradeType) {
		set("trade_type", tradeType);
	}

	public java.lang.String getTradeType() {
		return get("trade_type");
	}

	public void setCreateTime(java.lang.String createTime) {
		set("create_time", createTime);
	}

	public java.lang.String getCreateTime() {
		return get("create_time");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

}
