package com.manage.dao.entity;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLogAccountFree<M extends BaseLogAccountFree<M>> extends Model<M> implements IBean {

	public void setLogId(java.lang.Integer logId) {
		set("log_id", logId);
	}

	public java.lang.Integer getLogId() {
		return get("log_id");
	}

	public void setVipNo(java.lang.String vipNo) {
		set("vip_no", vipNo);
	}

	public java.lang.String getVipNo() {
		return get("vip_no");
	}

	public void setBeforeBalance(java.lang.String beforeBalance) {
		set("before_balance", beforeBalance);
	}

	public java.lang.String getBeforeBalance() {
		return get("before_balance");
	}

	public void setTradeBalance(java.lang.String tradeBalance) {
		set("trade_balance", tradeBalance);
	}

	public java.lang.String getTradeBalance() {
		return get("trade_balance");
	}

	public void setAfterBalance(java.lang.String afterBalance) {
		set("after_balance", afterBalance);
	}

	public java.lang.String getAfterBalance() {
		return get("after_balance");
	}

	public void setTradeType(java.lang.Integer tradeType) {
		set("trade_type", tradeType);
	}

	public java.lang.Integer getTradeType() {
		return get("trade_type");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public void setLogType(java.lang.String logType) {
		set("log_type", logType);
	}

	public java.lang.String getLogType() {
		return get("log_type");
	}

}
