package com.manage.dao.entity;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSms<M extends BaseSms<M>> extends Model<M> implements IBean {

	public void setSmsId(java.lang.Integer smsId) {
		set("sms_id", smsId);
	}

	public java.lang.Integer getSmsId() {
		return get("sms_id");
	}

	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}

	public java.lang.String getPhone() {
		return get("phone");
	}

	public void setVerifyCode(java.lang.String verifyCode) {
		set("verify_code", verifyCode);
	}

	public java.lang.String getVerifyCode() {
		return get("verify_code");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public void setExpTime(java.util.Date expTime) {
		set("exp_time", expTime);
	}

	public java.util.Date getExpTime() {
		return get("exp_time");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
