package com.manage.dao.entity;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserBase<M extends BaseUserBase<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setVipNo(java.lang.String vipNo) {
		set("vip_no", vipNo);
	}

	public java.lang.String getVipNo() {
		return get("vip_no");
	}

	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}

	public java.lang.String getPhone() {
		return get("phone");
	}

	public void setIdCard(java.lang.String idCard) {
		set("id_card", idCard);
	}

	public java.lang.String getIdCard() {
		return get("id_card");
	}

	public void setRealName(java.lang.String realName) {
		set("real_name", realName);
	}

	public java.lang.String getRealName() {
		return get("real_name");
	}

	public void setShareBonusRate(java.lang.String shareBonusRate) {
		set("share_bonus_rate", shareBonusRate);
	}

	public java.lang.String getShareBonusRate() {
		return get("share_bonus_rate");
	}

	public void setLockNum(java.lang.String lockNum) {
		set("lock_num", lockNum);
	}

	public java.lang.String getLockNum() {
		return get("lock_num");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public void setLoginTimes(java.lang.Integer loginTimes) {
		set("login_times", loginTimes);
	}

	public java.lang.Integer getLoginTimes() {
		return get("login_times");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
