package com.manage.dao.model;

import com.manage.dao.entity.BaseAccountFree;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AccountFree extends BaseAccountFree<AccountFree> {
	public static final AccountFree dao = new AccountFree().dao();
}
