package com.manage.dao.model;

import com.manage.dao.entity.BaseAccountLock;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AccountLock extends BaseAccountLock<AccountLock> {
	public static final AccountLock dao = new AccountLock().dao();
}
