package com.manage.dao.model;

import com.manage.dao.entity.BaseLogAccountFree;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LogAccountFree extends BaseLogAccountFree<LogAccountFree> {
	public static final LogAccountFree dao = new LogAccountFree().dao();
}
