package com.manage.dao.model;

import com.manage.dao.entity.BaseSms;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Sms extends BaseSms<Sms> {
	public static final Sms dao = new Sms().dao();
}
