package com.manage.dao.model;

import com.manage.dao.entity.BaseSysParameter;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysParameter extends BaseSysParameter<SysParameter> {
	public static final SysParameter dao = new SysParameter().dao();
}
