package com.manage.dao.model;

import com.manage.dao.entity.BaseTbSysSequence;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbSysSequence extends BaseTbSysSequence<TbSysSequence> {
	public static final TbSysSequence dao = new TbSysSequence().dao();
}
