package com.manage.dao.model;

import com.manage.dao.entity.BaseUserBase;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserBase extends BaseUserBase<UserBase> {
	public static final UserBase dao = new UserBase().dao();
}
